### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#10]

**Comment by dillonwilliams** [comment]
A decent end-to-end example might be a suite that does some basic image transformations and filters on a small image checked into the repo. Is this what we're looking for? What would `metrics` be on something like that?

**Comment by johndgiese** [comment]
This seems like a good example to me.  Maybe some good metrics would be the "mean", "median", and "max" values of the filtered image?

**Comment by johndgiese** [comment]
You could also generate an image on the fly using `numpy`, instead of checking an image in.  This may be nice if you wanted to have multiple cases.
