### ISSUE TITLE
Find a way to avoid needing `.hdatsuites`

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#13]
As usual, it would be good to write out your design here so we can discuss, before implementing.

**Comment by dillonwilliams** [comment]
This can be done with:
1. Use a configurable suffix, with default `_hdat`
2. Search for all .py files with the suffix in the `<cwd>/tests` and `<cwd>` dirs, and maybe other dirs. (?)
3. Load the modules with the suffix, check for subclasses of `hdat.suite`, then continue to existing functionality.

The one that I'm not sure about is _2_. Should we search all directories 1 or 2 deep from `cwd` for modules with the suffix?

**Comment by johndgiese** [comment]
I like this plan.  I think for now we don't need to make the suffix configurable.  I.e. we can just require the `_hdat` suffix.

Concerning (2), I think we should use pytest as a starting place.  I.e., unless there is a good reason to do something different, we can just do what they do.

How were you thinking of implementing (3)?

**Comment by dillonwilliams** [comment]
For (2), pytest will go through your whole filesystem if you let it. Their collector https://github.com/pytest-dev/pytest/blob/master/_pytest/python.py has some bells and whistles on top of that. 

(3) is something like this:
```
name = '<something>_hdat.py'
suites = []
os.path(name).pyimport()
for member in inspect.getmembers(sys.modules[name]):
    if inspect.isclass(member) and 'hdat.suite' in inspect.mro(member):
        suites.append(member)
```

**Comment by johndgiese** [comment]
For (2) I think it makes sense for us to start by looking through all files below the CWD for those that end with `_hdat.py`.

Your sample implementation for (3) looks great.

**Comment by johndgiese** [comment]
My logic on keeping the collection process simple is:

For now, our main concern is having something we can use internally.  Internally, I am pretty sure that we are fine using `_hdat.py`.

If we see a good number of people using hdat, then I think it will make sense to add more customizability for features like this.

Do you think this is a reasonable approach?
