### ISSUE TITLE
Further simplifications to the HDAT API

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#25]
We should consider even further simplifications to the HDAT Api in a future pre v1 version.

For example, we should discuss:

1. Removing the need for an `id` attribute on `hdat.Suite` classes
2. Whether the current `hdat.MetricsChecker` method names are intuitive.  For example, @zach-waggoner made a good point that `.close` is usually used to be the opposite of `.open`, thus perhaps `.close` should maybe be renamed to `.isclose`.

It would be good to discuss this with the whole team to see if there are other possible improvements.

**Comment by russellkan** [comment]
What's the rationale behind removing `suite_id`? It seems to be used extensively in the operations and important as an identifier in `show` and `diff`.

The second point definitely makes sense as `.close` just calls `._isclose` to check if a value is near the golden value. Would we want to rename it to `.isclose` if there already is a method `_isclose`, or perhaps something else such as `.similar` or perhaps `.near_exact` to match the method `.exact`?

@dillonwilliams What do you think?

**Comment by johndgiese** [comment]
Regarding your first question: It looks like the code already doesn't require an explicit `id` on the Suite classes (see https://github.com/innolitics/hdat/blob/master/hdat/suite.py#L49).  Note that we definitely still need a `suite_id`, I just don't want users to need to explicitly set one.

@dillonwilliams can answer your other questions.
