### ISSUE TITLE
Create a small assertion library for metrics

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#4]
We would want to keep the number of supported assertions quite small.

**Comment by johndgiese** [comment]
It would be worth sketching out the function signatures here before implementing them, so we can talk through uses cases.

**Comment by dillonwilliams** [comment]
We can start out with something like this in `suite.py`:
```python
def basic_diff(old, new, float_abs_tol=0.0):
    if old.keys() != new.keys():
        return False, f'Metric(s) in golden result {old.difference(new)} were missing from the new run'

    for key, old_val in old:
        if type(old_val) == float:
            if not math.isclose(old_val, new[key], abs_tol=float_abs_tol):
                msg = f'Metric {key} value {new[key]} did not match golden value {old_val} within {float_abs_tol}'
                return False, msg
        elif old_val != new[key]:
            return False, f'Metric {key} value {new[key]} did not match golden metric value {old_val}'

    return True, f'New metrics fully matched old metrics'
```

**Comment by johndgiese** [comment]
I think we will need something more granular, since usually each metric will have different tolerances.  Also, some metrics are allowed to increase as much as they like, so long as they don't decrease too much, and vice-versa.

**Comment by johndgiese** [comment]
Perhaps we could have a high-level function that indicates all keys, how they can change, and tolerances?

**Comment by dillonwilliams** [comment]
That puts some work on the user to define their metrics in a static way that they didn't before, something like this might fit in better with the existing suites:
```python
# in the user's suite subclass
def check(old, new):
    checker = MetricsChecker(old, new) # checks that keys match first
    checker.isexact('metric1', 'metric2', 'metric3')
    checker.allow_greater('metric_can_increase')
    checker.isclose('float_metric1', 'float_metric2', abs_tol=0.1)
    checker.isclose('float_metric3', abs_tol=0.0)
    return checker.result(), checker.msg()
```
This also has the advantage of displaying all unmatched metrics, not just the first one.

**Comment by johndgiese** [comment]
Sorry for the delay; just got out of a long meeting.

Originally, I was envisioning separate assertion functions for `change`, `increase`, `decrease` etc., but having a single class (or function) perform all the assertions is nice because it can combine the error messages together.  Thus, I like your approach better.

I do think we can still simplify more.  Perhaps we could avoid using a class if we did something like:

```
def check(old, new):
    return metrics_checker(old, new, {
        'metric1': { ... },
        'metric2': { ... },
    })
```

This removes the need to create an object and then call `checker.result(), checker.msg()` at the end...

That said, using methods would make auto-complete work better.  And keyword arguments are less verbose than dict literals.

If we do go with the method approach, I don't think we need to bother supporting multiple metrics per invocation.  E.g. `checker.isexact('metric1').  IMO it is slightly confusing and not necessary, since you could just call the method multiple times.
