### ISSUE TITLE
Consider simplifying the APIs

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#7]
We should think through the:

1. API for the HDAT suites
2. the CLI

and try and find places where we can simplify them.

**Comment by johndgiese** [comment]
This was probably obvious, but we should talk through any changes to the Suite class API before implementing them.

**Comment by dillonwilliams** [comment]
Changes to suite class API so far: removed `build_result_id`, removed `report`, changed `verify` to `check`.

Idea for CLI (not really a simplification): add an `hdat list` to list suites that have been discovered in #13

**Comment by johndgiese** [comment]
What need would `hdat list` fulfill that `hdat run --collect-only` doesn't?

**Comment by johndgiese** [comment]
All other changes are great!

**Comment by dillonwilliams** [comment]
`hdat run --collect-only` does exactly that, but I forgot it existed. Will add to the argparse help strings.

**Comment by johndgiese** [comment]
We should consider replacing `hdat run --collect-only` with `hdat list`, however.

For starters, `hdat list` is shorter and probably easier to remember.  I don't know which form is more "standard".  I feel like both are commonly used.

**Comment by johndgiese** [comment]
Maybe look into it a bit, and use your best judgement regarding which form is better.

**Comment by dillonwilliams** [comment]
Pull request #16 changes it to `hdat list`. I think this is more straightforward. Will close this after that pull request is merged unless there are other concerns. I think the API is pretty clean overall.

**Comment by dillonwilliams** [comment]
No more changes to make here. `suite.diff` is going to stay, with an example added to clarify its purpose.
