### ISSUE TITLE
Results reporting

### ISSUE THREAD

**Issue by johndgiese** [innolitics/hdat#9]
We need a way to generate tables with the results of running a test suite.  Perhaps the API could work something like:

`hdat csv --keys=test_id,metrics.a,metrics.b my_test_suite`

and would print the following to standard output:

```
test_id, metrics.a, metrics.b
my_test_suite/case-001, 13.1, 32.1
my_test_suite/case-002, 22.1, 40.4
```

**Comment by johndgiese** [comment]
@yujanshrestha and @dillonwilliams what do you guys think about the API described in this issue?

**Comment by dillonwilliams** [comment]
It would be good to make `--keys` optional and just have it show everything. Also, would it be helpful to have the golden results available in the output? There isn't a resultspec that fetches goldens right now so it might need to be another option. The golden results could either be rows or columns.

**Comment by johndgiese** [comment]
@dillonwilliams these are both great ideas.  Having `--keys` (or whatever name we use for the flag) be optional would make using the subcommand much easier and more pleasant.  E.g., you won't have to look up the names of the keys in order to make a dump.

I don't like exceptions, but perhaps we should ignore the `context.*` keys by default?  The context often has big objects that we would not want to dump into a CSV.  That said, I can imagine wanting to pull keys out of the context sometimes too...

Adding a resultspec for the Goldens is also a great idea.

---

On another note, what happens if we one result spec has more keys than another?  E.g., we could run into the following scenarios:

Missing key in later result
1. A, B, C
2. A, C, D

New key in later result
1. A, B, C
2. A, B, C, D

**Comment by dillonwilliams** [comment]
I agree it should be metrics only, those are the "easily comparable summaries" that are used to compare the runs. I think the cell should just be blank if the metric isn't available, since the column specifies the metric for all runs.

**Comment by johndgiese** [comment]
I think putting "blanks" in for missing values makes a lot of sense.

Sounds good, so probably the default keys should be:

- a few hard-coded top-level fields (e.g. `result_id`, `run_on`)
- all of the metrics.

Perhaps one way to encode this is to support asterisks in the key spec.  Thus the default value for the `--keys` field would be `--keys 'case_id,result_id,run_on,gith_hash,metrics.*'`.  Does that seem reasonable?

I guess we will need to make two passes through the results in order to support any wild-card key specifiers.  The first pass will find the union of all keys present (e.g. in the cases from my previous email this would be A, B, C, D).  The second pass would be to print results.  If there are `KeyErrors` then we just fill in a blank.  If all the keys are specified up-front we won't need two passes.

**Comment by johndgiese** [comment]
We will need to be careful to not have all of the `results` in memory at once, since the `context` can be quite large... maybe we should make the context lazy-load for performance reasons?
